package model;

public enum NotificationTypes {
    RUNODE_NAME_CHANGED,
    RUNODE_REMOVE_FROM_PARENT,
    RUNODECOMPOSITE_ADD,
    RUNODECOMPOSITE_REMOVE,
    PRESENTATION_NEW_AUTHOR,
    PRESENTATION_NEW_IMAGE_PATH,
    ADD_SLOT,
    REMOVE_SLOT,
    SLOT_CHANGED_CONTENT,
    REPAINT_SLOTVIEWS,
    ERROR
}
