package model;

public enum NotificationTypes {
    RUNODE_NAME_CHANGED,
    RUNODECOMPOSITE_ADD,
    RUNODECOMPOSITE_REMOVE,
    PRESENTATION_NEW_AUTHOR,
    PRESENTATION_NEW_IMAGE_PATH,
    ADD_SLOT,
    REMOVE_SLOT,
    REPAINT_SLIDEVIEWS,
    ERROR
}
